#!/bin/bash

#Make required directories
mkdir ~/bin ~/github #Make folders to store scripts and github clones

#Set up bash profile and set PATH variable
export PATH=~/bin:"$PATH" #Set your local bin folder to the PATH
echo '#scripts to run on login' >> ~/.bashrc #Adds the line in quotes to .bashrc
echo '~/bin/onlogin' >> ~/.bashrc #Adds the line in quotes to .bashrc, thereby causing the onlogin script to run on login
. .bashrc #Reload .bashrc to reset PATH

#Install git and wget
sudo apt-get update && sudo apt-get upgrade -y #First update the apt repos and upgrade any packages that need upgrading
sudo apt-get install git wget -y #Now install git and wget

#Get all the scripts from the Github repo
git clone https://github.com/Marzogh/LinuxScriptCache.git ~/github/LinuxScriptCache #Clone Linux script cache from Github
cp ~/github/LinuxScriptCache/bash_scripts/onlogin ~/bin/onlogin #Move onlogin to ~/bin
sudo chmod+x ~/bin/* #Make everything in ~/bin executable
onlogin #Run the onlogin script

echo 'System is ready to go!'

exit 0
