#!/bin/bash

echo "Checking internet connectivity..."
ping -c 5 www.google.com>>/dev/null

if [ $? == 0 ]; then
	echo "Connected to the internet"
	# Pull latest changes from github repos

	#LinuxShellScripts repo
	cd ~/github/LinuxScriptCache
	git pull
	cd ~

	#Update the local scripts
	echo "Copying updated scripts to ~/bin"
	sudo cp ~/github/LinuxScriptCache/bash_scripts/* ~/bin
	sudo chmod +x ~/bin/*
	echo "User scripts updated and made executable"

	# Check to see if apt-get update has been run in the last day
	if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]; then
		# Update the list of apt repos
		echo "Getting apt repository update"
		sudo apt-get update
	else
		echo "Apt index is up to date"
	fi

else
	echo "Not connected to the internet. Exiting onlogin script"
fi

exit 0
