#!/bin/bash

# Pull latest changes from github repos

	#LinuxShellScripts repo
	cd ~/github/LinuxScriptCache
	git pull
	cd ~

	#Update the local scripts
	echo Copying updated scripts to ~/bin
	sudo cp ~/github/LinuxScriptCache/bash_scripts/* ~/bin
	sudo chmod +x ~/bin/*
	echo User scripts updated and made executable.

# Update the list of apt repos
echo Getting apt repository update
sudo apt-get update

#
