#!/bin/bash

# Pull latest changes from github repos

	#LinuxShellScripts repo
	cd ~/github/LinuxScriptCache
	git pull
	cd ~

	#Update the local scripts
	sudo cp ~/github/LinuxScriptCache/bash_scripts/* ~/bin
	sudo chmod +x ~/bin/*

# Update the list of apt repos
sudo apt-get update

#
