#!/usr/bin/env bash
echo $BASH_VERSION

# Setup wireless networking
  sudo service networking stop #Stop wireless networking service
  sudo mv /boot/wpa_supplicant.conf ~/wpa_supplicant.conf #Move wpa_supplicant.conf to home folder
  sudo bash -c 'cat /etc/wpa_supplicant/wpa_supplicant.conf >> ~/wpa_supplicant.conf' #Appends the contents of the current wpa_supplicant to the end of the wpa_supplicant file in the home folder
  sudo chmod 600 ~/wpa_supplicant.conf #Set correct permissions on wpa_supplicant
  sudo mv ~/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf #Move wpa_supplicant to the right place
  sudo mv /boot/uq-net-ca.pem /etc/ssl/certs/uq-net-ca.pem #Move CA certificate to the right place (if required)
  sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -B #Fire up the network

exit 0
