#!/usr/bin/env bash
echo $BASH_VERSION

#Back up the current wpa_supplicant configuration
sudo cp /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf.bak

#Apply the new wpa_supplicant configuration
sudo cp /etc/wpa_supplicant/$1 /etc/wpa_supplicant/wpa_supplicant.conf

sudo dhclient -r wlan0
sudo ifdown wlan0
sudo ifup wlan0
sudo dhclient -v wlan0

echo
iwconfig wlan0
ifconfig wlan0
